### ISSUE TITLE
The Wire.endTransmission() should not be used together with Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [khartinger/ePaperDisplay_D1mini#1]
In the file "ePaperDisplay_D1mini/D1_Epd0154bw_BME280_mqtt_sleep/D1_class_BME280.cpp" there is a Wire.endTransmission() after the Wire.requestFrom(). That Wire.endTransmission() can be removed.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by khartinger** [comment]
Thank you

**Comment by Koepel** [comment]
When searching Github for the wrong use of the Wire library, your repository came up again. In the file "ePaperDisplay_D1mini/D1_Epd0290bw_mqtt_sleep_Weather1/src/bh1750/D1_class_BH1750.cpp" there is a `Wire.endTransmission()` after a `Wire.requestFrom()` and it is still in other files as well.
